# Generated by Django 6.0.1 on 2026-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("MANAGER", "Manager"),
                    ("DEPUTY", "Deputy"),
                    ("OPERATOR", "Operator"),
                ],
                default="OPERATOR",
                max_length=20,
            ),
        ),
    ]
